[general]
import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/gruvbox_dark.toml"
  # "~/.config/alacritty/gruvbox_medium_dark.toml"
  # "~/.config/alacritty/gruvbox_light.toml"
  "~/.config/alacritty/hackstling.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 6.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window] 
  padding = { x = 4, y = 4}
  opacity = 0.95
