"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[](bg:yellow fg:bg1)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:purple)\
$docker_context\
[](fg:purple bg:bg1)\
$time\
[ ](fg:purple)\
$line_break$character
"""

palette = 'hackstling'

[palettes.hackstling]
bg0 = '#2C2C36'
bg1 = '#353540'
fg0 = '#D9D0E2'
fg1 = '#B8B0C8'
gray = '#5C5C70'
blue = '#00BFFF'
green = '#00FF41'
orange = '#FF4500'  # Neon for accents/errors
yellow = '#FF8C00'  # Yellower orange for bgs (softer, less red)
purple = '#B58ACF'

[os]
disabled = false
style = "bg:bg1 fg:fg0"
[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:bg1 fg:fg0"
style_root = "bg:bg1 fg:fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:bg1 bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $branch ](fg:bg1 bg:green)]($style)'

[git_status]
style = "bg:blue"
format = '[[($all_status$ahead_behind )](fg:bg1 bg:green)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:bg1 bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $context) ](fg:fg0 bg:purple)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:purple"
format = '[[  $time ](fg:bg1 bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:orange)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:blue)'
